services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - task-user-network

  postgres-keycloak:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - keycloak-network
    restart: unless-stopped

  keycloak:
    #image: quay.io/keycloak/keycloak:21.0.1
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
    command: start-dev
    ports:
      - "8081:8080"
    depends_on:
      - postgres-keycloak
    networks:
      - keycloak-network
      - task-user-network
      - ldap-network
    restart: unless-stopped

networks:
  keycloak-network:
  task-user-network:
    external: true
  ldap-network:
    external: true

volumes:
  postgres_keycloak_data: