services:
  postgres:
    image: postgres:15
    container_name: postgres-task
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: task_service
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - postgres_task_data:/var/lib/postgresql/data
    networks:
      - task-postgres-network

  task-service:
    build: .
    container_name: task-service
    ports:
      - 8083:8083
    environment:
      USER_SERVICE_URL: http://user-service:8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-task:5432/task_db
      SPRING_DATASOURCE_USERNAME: task_service
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_RABBITMQ_HOST: rabbitmq
      spring_security_oauth2_client_provider_keycloak_token-uri: http://keycloak:8080/realms/task-management-realm/protocol/openid-connect/token
      spring_security_oauth2_resourceserver_jwt_jwk-set-uri: http://keycloak:8080/realms/task-management-realm/protocol/openid-connect/certs
    depends_on:
      - postgres
    networks:
      - task-postgres-network
      - task-user-network

networks:
  task-postgres-network:
  task-user-network:
    external: true

volumes:
  postgres_task_data: